src/accounts/urls.py
from django.urls import path

from . import views
from django.conf.urls import url,include

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
]

src/home/urls.py
from django.urls import path

from .views import home_page

app_name = 'home'
urlpatterns = [
    path('', home_page, name='home'),
]

src/koohnavard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('plan/', include('planning.urls', namespace="planning")),
    path('club/', include('participation.urls', namespace='participation')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('test', lambda req: render(req, 'base.html', {}), name='test'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/registration/password_reset_form.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

src/participation/urls.py
from django.urls import path

from . import views

app_name = 'participation'
urlpatterns = [
    path('', views.clubs_list_view, name='clubs_list'),
    path('<int:club_id>/', views.club_profile_view, name='club_view'),
    path('<int:club_id>/edit/', views.edit_club_view, name='club_edit'),
    path('<int:club_id>/requests/', views.club_requests_view, name='club_join_requests'),
    path('new/', views.create_club_view, name='club_create'),
    path('<int:club_id>/join/', views.join_request_view, name='club_join'),
    path('<int:club_id>/leave/', views.leave_request_view, name='club_leave'),
    path('admin/reqs/answer/<int:req_id>/<int:accept>/', views.answer_request_view, name='answer_club_join_request'),
    path('admin/members/kick/<int:req_id>/', views.kick_club_member_view, name='kick_club_member'),
]

src/planning/urls.py
from django.urls import path

from . import views

app_name = 'planning'
urlpatterns = [
    path('', views.plans_list_view, name='all_plans_list'),
    path('club/<int:club_id>', views.plans_list_view, name='plans_list'),
    path('<int:plan_id>/', views.plan_profile_view, name='plan_view'),
    path('edit/<int:plan_id>', views.edit_plan_view, name='plan_edit'),
    path('<int:club_id>/new/', views.create_plan_view, name='plan_create'),
    path('preregister/<int:plan_id>/', views.plan_participant_preregister, name='plan_participant_preregister'),
    path('<int:plan_id>/members/', views.plan_members_and_requests_view, name='plan_join_members_and_requests'),
    path('admin/reqs/answer/<int:req_id>/<str:accept>/', views.answer_request_view, name='answer_plan_join_request'),

]

src/templates/base-menuless.html
{% load static %}
{% load i18n %}

<html>
    <head>
        <meta charset="utf-8">
        <title>Koohnavard</title>
        <link rel="stylesheet" href="{% static 'dadashi/bootstrap/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="{% static 'dadashi/bootstrap/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="{% static 'dadashi/bootstrap/popper.min.js' %}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="{% static 'dadashi/bootstrap/bootstrap.min.js' %}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="{% static 'dadashi/bootstrap/bootstrap-rtl.min.css' %}">

        <link rel="stylesheet" href="{% static 'dadashi/css/style.css' %}">
    </head>

    <body onload="main()">
        <div class="row fill-h">
            <div class="col-sm-2 bg-dark text-white" align="center">
                {% block menu %}
                {% endblock %}
            </div>
            <div id="notif-box" class="col-sm-3">
            </div>
            <div class="col-sm-10" id="content">
                <nav aria-label="breadcrumb" style="width: 99%">
                    <ol class="breadcrumb">
                        {% block title %}
                        {% endblock %}
                    </ol>
                </nav>
                <br />
                <div class="row">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

src/templates/base.html
{% extends 'base-menuless.html' %}

{% load static %}
{% load i18n %}

{% block menu %}

<img src="{% static 'pics/logo.png' %}" class="logo"></img>

{% if user.is_authenticated %}
<hr class="sidebar-hr" />
<div class="navbar menu-item">
    <a href="{% url 'accounts:profile' %}" class="btn btn-link text-menuitem">
        {% trans "Profile" %}
    </a>
</div>
{% endif %}

<div class="navbar menu-item">
    <div class="dropdown menu-dropdown">
        <button type="button" class="btn btn-link text-menuitem dropdown-toggle" id="clubsDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% trans "clubs" %}
        </button>
        <div class="dropdown-menu" aria-labelledby="clubsDropdownButton">
            <a class="dropdown-item" href="{% url 'participation:clubs_list' %}">
                {% trans "list" %}
            </a>
            <a class="dropdown-item" href="{% url 'participation:club_create' %}">
                {% trans "new" %}
            </a>
        </div>
    </div>
</div>
<hr class="sidebar-hr" />
<div class="navbar menu-item">
    <a href="{% url 'planning:all_plans_list' %}" class="btn btn-link text-menuitem">
        {% trans "plans" %}
    </a>
</div>
{% if user.is_authenticated %}
<hr class="sidebar-hr" />
<div class="navbar menu-item">
    <a href="{% url 'accounts:logout' %}" class="btn btn-link text-menuitem">
        {% trans "logout" %} ({{ user.username }})
    </a>
</div>
{% else %}
<hr class="sidebar-hr" />
<div class="navbar menu-item">
    <a href="{% url 'accounts:login' %}" class="btn btn-link text-menuitem">
        {% trans "login" %}
    </a>
</div>
<hr class="sidebar-hr" />
<div class="navbar menu-item">
    <a href="{% url 'accounts:register' %}" class="btn btn-link text-menuitem">
        {% trans "register" %}
    </a>
</div>
{% endif %}

{% endblock %}