src/home/urls.py
from django.urls import path

from .views import home_page

app_name = 'home'
urlpatterns = [
    path('', home_page, name='home'),
]

src/koohnavard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('plan/', include('planning.urls', namespace="planning")),
    path('club/', include('participation.urls', namespace='participation')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('test', lambda req: render(req, 'base.html', {}), name='test'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/registration/password_reset_form.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

src/participation/urls.py
from django.urls import path

from . import views

app_name = 'participation'
urlpatterns = [
    path('', views.clubs_list_view, name='clubs_list'),
    path('<int:club_id>/', views.club_profile_view, name='club_view'),
    path('<int:club_id>/edit/', views.edit_club_view, name='club_edit'),
    path('<int:club_id>/requests/', views.club_requests_view, name='club_join_requests'),
    path('new/', views.create_club_view, name='club_create'),
    path('<int:club_id>/join/', views.join_request_view, name='club_join'),
    path('<int:club_id>/leave/', views.leave_request_view, name='club_leave'),
    path('admin/reqs/answer/<int:req_id>/<int:accept>/', views.answer_request_view, name='answer_club_join_request'),
    path('admin/members/kick/<int:req_id>/', views.kick_club_member_view, name='kick_club_member'),
]

src/planning/urls.py
from django.urls import path

from . import views

app_name = 'planning'
urlpatterns = [
    path('', views.plans_list_view, name='all_plans_list'),
    path('club/<int:club_id>', views.plans_list_view, name='plans_list'),
    path('<int:plan_id>/', views.plan_profile_view, name='plan_view'),
    path('edit/<int:plan_id>', views.edit_plan_view, name='plan_edit'),
    path('<int:club_id>/new/', views.create_plan_view, name='plan_create'),
    path('preregister/<int:plan_id>/', views.plan_participant_preregister, name='plan_participant_preregister'),
    path('<int:plan_id>/members/', views.plan_members_and_requests_view, name='plan_join_members_and_requests'),
    path('admin/reqs/answer/<int:req_id>/<str:accept>/', views.answer_request_view, name='answer_plan_join_request'),

]

src/participation/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _

from planning.models import Plan


class Club(models.Model):
    title = models.CharField(max_length=200,
                             blank=False,
                             null=False,
                             unique=True, verbose_name=_('title'))
    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE, verbose_name=_('owner'))

    def __str__(self):
        return self.title


    @property
    def members_cnt(self):
        return ClubMember.objects.filter(club=self).filter(pending=False).count()


    @property
    def plans_cnt(self):
        return Plan.objects.filter(club=self).count()


class ClubMember(models.Model):
    club = models.ForeignKey(Club,
                             on_delete=models.CASCADE, verbose_name=_('club'))
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE, verbose_name=_('user'))

    pending = models.BooleanField(default=True, verbose_name=_('pending'))

src/participation/forms.py
from django import forms

from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['title']

src/participation/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponseBadRequest

from .models import Club, ClubMember
from .forms import ClubForm


def clubs_list_view(request):
    if request.user.is_authenticated:
        my_reqs = ClubMember.objects.filter(user=request.user, pending=False)
        my_clubs = list(map(lambda req: req.club, my_reqs))

        pending_reqs = ClubMember.objects.filter(user=request.user, pending=True)
        pending_clubs = list(map(lambda req: req.club, pending_reqs))

        other_clubs = list(filter(lambda club: club not in my_clubs and club not in pending_clubs, Club.objects.all()))
        return render(request,
                'participation/clubs_list.html',
                {
                    'auth': True,
                    'my_clubs': my_clubs,
                    'pending_clubs': pending_clubs,
                    'other_clubs': other_clubs,
                })
    else:
        return render(request,
                'participation/clubs_list.html',
                {
                    'auth': False,
                    'clubs': Club.objects.all(),
                })


def club_profile_view(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    members = club.clubmember_set.filter(pending=False)
    req = ClubMember.objects.filter(user=request.user, club=club).first()
    return render(request,
            'participation/club_profile.html',
            {
                'club': club,
                'members': members,
                'is_mine': club.owner == request.user,
                'is_member': req is not None and not req.pending,
                'is_pending': req is not None and req.pending,
            })


@login_required
def edit_club_view(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    if club.owner != request.user:
        return HttpResponseForbidden()
    form = ClubForm(request.POST or None, instance=club)
    if request.method == 'POST':
        if form.is_valid():
            club = form.save()
            return HttpResponseRedirect(reverse('participation:club_view',
                args=(club.id,)))
    return render(request,
            'participation/club_edit.html',
            {
                'form': form,
                'club': club,
            })


@login_required
def club_requests_view(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    is_owner = club.owner == request.user
    reqs = ClubMember.objects.filter(club=club, pending=True)
    members = ClubMember.objects.filter(club=club, pending=False)
    return render(request,
            'participation/club_requests.html',
            {
                'reqs': reqs if is_owner else [],
                'members': members,
                'club': club,
                'is_owner': is_owner,
            })


@login_required
def create_club_view(request):
    form = ClubForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            club = form.save(commit=False)
            club.owner = request.user
            club.save()
            ClubMember.objects.create(user=club.owner, club=club, pending=False)
            return HttpResponseRedirect(reverse('participation:club_view',
                args=(club.id,)))
    return render(request,
            'participation/club_create.html',
            {'form': form})


@login_required
def join_request_view(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    member = ClubMember.objects.filter(club=club, user=request.user)
    if member.count() != 0 or member.first() == club.owner:
        return HttpResponseBadRequest()
    ClubMember.objects.create(user=request.user, club=club)
    return HttpResponseRedirect(reverse('participation:clubs_list'))


@login_required
def leave_request_view(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    member = ClubMember.objects.filter(club=club, user=request.user)
    if member.count() == 0 or member.first() == club.owner:
        return HttpResponseBadRequest()
    member.delete()
    return HttpResponseRedirect(reverse('participation:clubs_list'))


@login_required
def answer_request_view(request, req_id, accept):
    req = get_object_or_404(ClubMember, pk=req_id)
    club = req.club
    if club.owner != request.user:
        return HttpResponseForbidden()
    if accept:
        req.pending = False
        req.save()
    elif req.user != club.owner:
        req.delete()
    return HttpResponseRedirect(reverse('participation:club_join_requests', args=(club.id,)))


@login_required
def kick_club_member_view(request, req_id):
    return answer_request_view(request, req_id, 0)

src/participation/templates/participation/club_card.html
{% load i18n %}

<div class="card club-card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title"> {{ club.title }} </h5>
        <p class="card-text"></p>
        <a href="{% url 'participation:club_view' club_id=club.id %}" class="card-link">{% trans "details" %}</a>
    </div>
</div>

src/participation/templates/participation/club_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'participation:clubs_list' %}">
        {% trans "clubs" %}
    </a>
</li>

<li class="breadcrumb-item active">
    {% trans "add club" %}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-3"></div>
<div class="col-sm-6">
    <div class="card card-form">
        <div class="card-header">
            {% trans "club properties" %}
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'participation:club_create' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <input name="" type="submit" class="btn btn-primary" value="{% trans 'add' %}" />
            </form>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
{% endblock %}

src/participation/templates/participation/club_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'participation:clubs_list' %}">
        {% trans "clubs" %}
    </a>
</li>

<li class="breadcrumb-item">
    <a href="{% url 'participation:club_view' club_id=club.id %}">
        {{ club.title }}
    </a>
</li>

<li class="breadcrumb-item active">
    {% trans "edit club" %}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-3"></div>
<div class="col-sm-6">
    <div class="card card-form">
        <div class="card-header">
            {% trans "properties" %}
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'participation:club_edit' club_id=club.id %}">
                {% csrf_token %}
                {{ form|crispy }}
                <input name="" type="submit" class="btn btn-primary" value="{% trans 'edit' %}" />
            </form>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
{% endblock %}

src/participation/templates/participation/club_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'participation:clubs_list' %}">
        {% trans "clubs" %}
    </a>
</li>

<li class="breadcrumb-item active">
    {{ club.title }}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-3" style="text-align: center;">
    <br />
    {% if not is_mine %}
        {% if is_member %}
            <a href="{% url 'participation:club_leave' club_id=club.id %}" class="text-danger">
                {% trans "leave" %}
            </a>
        {% elif is_pending %}
            <a href="{% url 'participation:club_leave' club_id=club.id %}" class="text-danger">
                {% trans "cancel request" %}
            </a>
        {% else %}
            <a href="{% url 'participation:club_join' club_id=club.id %}" class="text-success">
                {% trans "join request" %}
            </a>
        {% endif %}
    {% else %}
        <a href="{% url 'participation:club_edit' club_id=club.id %}">
            {% trans "edit" %}
        </a>
        <hr class="club-ops-hr">
        <a href="{% url 'planning:plan_create' club_id=club.id %}">
            {% trans "new plan" %}
        </a>
    {% endif %}
</div>
<div class="col-sm-7">
    <br />
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">
                    {% trans "owner" %}
                </th>
                <td>
                    {{ club.owner.first_name }}
                    {{ club.owner.last_name }}
                </td>
            </tr>
            <tr>
                <th scope="row">
                    {% trans "members" %}
                </th>
                <td>
                    {{ club.members_cnt }} {% trans "persons" %}
                    (<a href="{% url 'participation:club_join_requests' club_id=club.id %}">{% trans "list" %}</a>)
                </td>
            </tr>
            <tr>
                <th scope="row">
                    {% trans "plans" %}
                </th>
                <td>
                    {{ club.plans_cnt }}
                    (<a href="{% url 'planning:plans_list' club_id=club.id %}">{% trans "list" %}</a>)
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div class="col-sm-2"></div>
{% endblock %}

src/participation/templates/participation/club_requests.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'participation:clubs_list' %}">
        {% trans "clubs" %}
    </a>
</li>

<li class="breadcrumb-item">
    <a href="{% url 'participation:club_view' club_id=club.id %}">
        {{ club.title }}
    </a>
</li>

<li class="breadcrumb-item active">
    {% trans "membership" %}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-1"></div>
<div class="col-sm-4">
    <h4>{% trans "members" %}</h4>
    <table class="table">
        <tbody>
            {% for req in members %}
            <tr>
                <td>{{ req.user.first_name }}</td>
                <td>{{ req.user.last_name }}</td>
                <td>
                {% if is_owner %}
                    <a href="{% url 'participation:kick_club_member' req_id=req.id %}" class="text-danger">{% trans "kick" %}</a>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="col-sm-1"></div>
{% if is_owner %}
<div class="col-sm-5">
    <h4>{% trans "pending requests" %}</h4>
    <table class="table">
        <tbody>
            {% for req in reqs %}
            <tr>
                <td>{{ req.user.first_name }}</td>
                <td>{{ req.user.last_name }}</td>
                <td>
                    <a href="{% url 'participation:answer_club_join_request' req_id=req.id accept=1 %}" class="text-success">
                        {% trans "accept" %}
                    </a>
                </td>
                <td>
                    <a href="{% url 'participation:answer_club_join_request' req_id=req.id accept=0 %}" class="text-danger">
                        {% trans "reject" %}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
<div class="col-sm-1"></div>
{% endblock %}

src/participation/templates/participation/clubs_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item active">{% trans "clubs" %}</li>
{% endblock %}

{% block content %}
<div class="col-sm-1"></div>
<div class="col-sm-10">
    {% if auth %}
        {% if my_clubs %}
            <h4>{% trans "my clubs" %}</h4>
            {% for club in my_clubs%}
                {% include 'participation/club_card.html' with club=club %}
            {% endfor %}
        {% endif %}

        {% if pending_clubs %}
            <br />
            <br />
            <h4>{% trans "pending clubs" %}</h4>
            {% for club in pending_clubs%}
                {% include 'participation/club_card.html' with club=club %}
            {% endfor %}
        {% endif %}

        {% if other_clubs %}
            <br />
            <br />
            <h4>{% trans "other clubs" %}</h4>
            {% for club in other_clubs%}
                {% include 'participation/club_card.html' with club=club %}
            {% endfor %}
        {% endif %}
    {% else %}
        <h4></h4>
        {% for club in clubs %}
            {% include 'participation/club_card.html' with club=club %}
        {% endfor %}
    {% endif %}
</div>
<div class="col-sm-1"></div>
{% endblock %}