src/home/urls.py
from django.urls import path

from .views import home_page

app_name = 'home'
urlpatterns = [
    path('', home_page, name='home'),
]

src/koohnavard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('plan/', include('planning.urls', namespace="planning")),
    path('club/', include('participation.urls', namespace='participation')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('test', lambda req: render(req, 'base.html', {}), name='test'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/registration/password_reset_form.html'), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

src/planning/urls.py
from django.urls import path

from . import views

app_name = 'planning'
urlpatterns = [
    path('', views.plans_list_view, name='all_plans_list'),
    path('club/<int:club_id>', views.plans_list_view, name='plans_list'),
    path('<int:plan_id>/', views.plan_profile_view, name='plan_view'),
    path('edit/<int:plan_id>', views.edit_plan_view, name='plan_edit'),
    path('<int:club_id>/new/', views.create_plan_view, name='plan_create'),
    path('preregister/<int:plan_id>/', views.plan_participant_preregister, name='plan_participant_preregister'),
    path('<int:plan_id>/members/', views.plan_members_and_requests_view, name='plan_join_members_and_requests'),
    path('admin/reqs/answer/<int:req_id>/<str:accept>/', views.answer_request_view, name='answer_plan_join_request'),

]

src/planning/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.


class Plan(models.Model):
    club = models.ForeignKey('participation.Club', null=False, on_delete=models.DO_NOTHING, verbose_name=_('club'))
    title = models.CharField(max_length=50, null=False, default="", verbose_name=_('title'))
    description = models.CharField(max_length=256, null=False, default="", verbose_name=_('description'))
    destination_address = models.CharField(max_length=256, null=False, default="",
                                           verbose_name=_('destination_address'))
    start_datetime = models.DateTimeField(verbose_name=_('start_datetime'))
    head_man = models.CharField(max_length=256, null=False, default="", verbose_name=_('head_man'))
    group_link = models.URLField(default="", verbose_name=_('group_link'))

    def __str__(self):
        return str(self.title) + " " + str(self.club)

    @property
    def head_man_user(self):
        return User.objects.get(username=self.head_man)


    @property
    def participants_cnt(self):
        return PlanParticipant.objects.filter(plan=self).filter(
            status=str(PlanParticipant.MemberStatus.ACCEPTED)).count()


class PlanParticipant(models.Model):
    class MemberStatus(models.TextChoices):
        PENDING = "PENDING",
        ACCEPTED = "ACCEPTED",
        REJECTED = "REJECTED",

        @classmethod
        def choices(cls):
            print(tuple((i.name, i.value) for i in cls))
            return tuple((i.name, i.value) for i in cls)

    plan = models.ForeignKey(Plan, null=False, on_delete=models.CASCADE, verbose_name=_('plan'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('user'))
    status = models.CharField(max_length=255, choices=MemberStatus.choices, verbose_name=_('status'))

src/planning/forms.py
from django import forms

from .models import Plan, PlanParticipant


class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ['title', 'description', 'destination_address', 'start_datetime', 'head_man', 'group_link']

src/planning/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.http.response import HttpResponseForbidden, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext as _

from participation.models import Club, ClubMember
from .forms import PlanForm
from .models import Plan, PlanParticipant


def plans_list_view(request, club_id=0):
    clubs = []
    if club_id > 0:
        clubs = Club.objects.filter(pk=club_id)
    elif club_id == 0:
        clubs = Club.objects.all()
    elif club_id == -1 and request.user.is_authenticated:
        memberships = ClubMember.objects.filter(user=request.user).filter(pending=False)
        clubs = map(lambda memb: memb.club, memberships)

    plans = []
    for club in clubs:
        plans += list(club.plan_set.all())
    my_plans = None
    if request.user.is_authenticated:
        my_plans = PlanParticipant.objects.filter(user=request.user, status=str(PlanParticipant.MemberStatus.ACCEPTED))
        my_plans = map(lambda memb: memb.plan, my_plans)
        my_plans = filter(lambda plan: plan in plans, my_plans)
        my_plans = list(my_plans)
        my_plans.sort(key=lambda plan: plan.start_datetime)
        my_plans.reverse()

    return render(request, 'planning/plans_list.html', {
        'plans': plans,
        'my_plans': my_plans,
    })


def plan_profile_view(request, plan_id):
    plan = get_object_or_404(Plan, pk=plan_id)
    plan_participant = None
    if request.user.is_authenticated and PlanParticipant.objects.filter(user=request.user, plan=plan).count():
        plan_participant = PlanParticipant.objects.get(user=request.user, plan=plan)
    return render(request,
                  'planning/plan_profile.html',
                  {'plan': plan,
                   'plan_participant': plan_participant})


@login_required
def edit_plan_view(request, plan_id):
    # TODO permissions and roles not implemented
    plan = get_object_or_404(Plan, pk=plan_id)
    plan_head_man_list = User.objects.filter(username=plan.head_man)
    if plan.club.owner != request.user and (len(plan_head_man_list) == 0 or plan_head_man_list.first() != request.user):
        return HttpResponseForbidden()
    form = PlanForm(request.POST or None, instance=plan)
    if request.method == 'POST':
        if form.is_valid():
            """ creating plan """
        """ adding head man to plan participant """

        plan = form.save(commit=False)
        if User.objects.filter(username=plan.head_man).count() != 0 and ClubMember.objects.filter(
                user=plan.head_man_user, pending=False, club=plan.club).count() != 0:
            plan.save()
            if PlanParticipant.objects.filter(user=plan.head_man_user, plan=plan).count() == 0:
                parti = PlanParticipant()
                parti.user = plan.head_man_user
                parti.plan = plan
                parti.MemberStatus = str(PlanParticipant.MemberStatus.ACCEPTED)
                parti.save()

            return HttpResponseRedirect(reverse('planning:plan_view',
                                                args=[plan.id]))
        else:
            form.add_error('head_man', _("Invalid head man username"))
            return render(request,
                          'planning/plan_edit.html', {
                              'form': form,
                              'plan': plan,
                          })
    return render(request,
                  'planning/plan_edit.html',
                  {'form': form, 'plan': plan})


@login_required
def create_plan_view(request, club_id):
    # TODO permissions and roles not implemented
    club = get_object_or_404(Club, pk=club_id)
    if request.user != club.owner:
        return HttpResponseForbidden()
    form = PlanForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            """ creating plan """
            """ adding head man to plan participant """

            plan = form.save(commit=False)
            parti = PlanParticipant()
            if User.objects.filter(username=plan.head_man).count() != 0 and ClubMember.objects.filter(
                    user=plan.head_man_user, pending=False, club=club).count() != 0:
                parti.user = plan.head_man_user

                plan.club = club

                parti.plan = plan
                parti.MemberStatus = str(PlanParticipant.MemberStatus.ACCEPTED)

                plan.save()
                parti.save()

                return HttpResponseRedirect(reverse('planning:plan_view',
                                                    args=[plan.id]))
            else:
                form.add_error('head_man', _("Invalid head man username"))
                return render(request,
                              'planning/plan_create.html', {
                                  'form': form,
                                  'club_id': club_id,
                              })

    return render(request,
                  'planning/plan_create.html', {
                      'form': form,
                      'club_id': club_id,
                  })


@login_required
def plan_participant_preregister(request, plan_id):
    # TODO permissions and roles not implemented - Check for user club registration
    plan = get_object_or_404(Plan, pk=plan_id)
    if PlanParticipant.objects.filter(user=request.user).filter(plan=plan).count():
        return HttpResponseBadRequest("you are already a part of this plan!")
    PlanParticipant.objects.create(user=request.user, status=str(PlanParticipant.MemberStatus.PENDING), plan=plan)
    return HttpResponseRedirect(reverse('planning:plan_view',
                                        args=[plan.id]))


@login_required
def plan_members_and_requests_view(request, plan_id):
    ## TODO for requests
    plan = get_object_or_404(Plan, pk=plan_id)
    members = PlanParticipant.objects.filter(plan=plan, status=str(PlanParticipant.MemberStatus.ACCEPTED))
    pending = PlanParticipant.objects.filter(plan=plan, status=str(PlanParticipant.MemberStatus.PENDING))
    if not ClubMember.objects.filter(club=plan.club, user=request.user).count():
        return HttpResponseForbidden()
    edit_access = False
    if plan.head_man_user == request.user or plan.club.owner == request.user:
        edit_access = True
    return render(request,
                  'planning/plan_members_and_requests.html',
                  {
                      'members': members,
                      'pending': pending if edit_access else [],
                      'plan': plan,
                      'edit_access': edit_access
                  })


@login_required
def answer_request_view(request, req_id, accept):
    req = get_object_or_404(PlanParticipant, pk=req_id)
    plan = req.plan
    if plan.head_man != str(request.user) and plan.club.owner != request.user:
        return HttpResponseForbidden()
    if accept == 'ACCEPT':
        req.status = PlanParticipant.MemberStatus.ACCEPTED
    elif accept == 'REJECT':
        req.status = PlanParticipant.MemberStatus.REJECTED
    req.save()
    return HttpResponseRedirect(reverse('planning:plan_join_members_and_requests', args=(plan.id,)))

src/planning/templates/planning/plan_card.html
{% load i18n %}

<div class="card club-card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title"> {{ plan.title }} </h5>
        <p class="card-text">{{ plan.description }}</p>
        <a href="{% url 'planning:plan_view' plan_id=plan.id %}" class="card-link">{% trans "details" %}</a>
    </div>
</div>

src/planning/templates/planning/plan_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'planning:plans_list' club_id=club_id %}">
        {% trans "plans" %}
    </a>
</li>

<li class="breadcrumb-item active">
    {% trans "add plan" %}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-3"></div>
<div class="col-sm-6">
    <div class="card card-form">
        <div class="card-header">
            {% trans "plan properties" %}
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'planning:plan_create' club_id=club_id %}">
                {% csrf_token %}
                {{ form | crispy}}
                <input type="submit" name="" value="{% trans 'add' %}"/>
            </form>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
{% endblock %}

src/planning/templates/planning/plan_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'planning:all_plans_list' %}">
        {% trans "plans" %}
    </a>
</li>

<li class="breadcrumb-item">
    <a href="{% url 'planning:plan_view' plan_id=plan.id %}">
        {{ plan.title }}
    </a>
</li>

<li class="breadcrumb-item active">
    {% trans "edit plan" %}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-3"></div>
<div class="col-sm-6">
    <div class="card card-form">
        <div class="card-header">
            {% trans "Plan Properties" %}
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'planning:plan_edit' plan_id=plan.id %}">
                {% csrf_token %}
                {{ form|crispy }}
                <input name="" type="submit" class="btn btn-primary" value="{% trans 'edit' %}" />
            </form>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
{% endblock %}

src/planning/templates/planning/plan_members_and_requests.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'planning:all_plans_list' %}">
        {% trans "plans" %}
    </a>
</li>

<li class="breadcrumb-item">
    <a href="{% url 'planning:plan_view' plan_id=plan.id %}">
        {{ plan.title }}
    </a>
</li>

<li class="breadcrumb-item active">
    {% trans "membership" %}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-1"></div>
<div class="col-sm-4">
    <h4>{% trans "members" %}</h4>
    <table class="table">
        <tr>
            <th>{% trans "first_name" %}</th>
            <th>{% trans "last_name" %}</th>
            {% if edit_access %}
            <th>{% trans "action" %}</th>
            {% endif %}
        </tr>
        <tbody>
        {% for req in members %}
        <tr>
            <td>{{ req.user.first_name }}</td>
            <td>{{ req.user.last_name }}</td>
            {% if edit_access %}

            <td>
                <a href="{% url 'planning:answer_plan_join_request' req_id=req.id accept='REJECT' %}"
                   class="text-danger">{% trans "kick" %}</a>
            </td>
            {% endif %}

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="col-sm-1"></div>
{%if pending %}
<div class="col-sm-5">
    <h4>{% trans "pending requests" %}</h4>
    <table class="table">
        <tbody>
        {% for req in pending %}
        <tr>
            <td>{{ req.user.first_name }}</td>
            <td>{{ req.user.last_name }}</td>
            {% if edit_access %}
            <td>
                <a href="{% url 'planning:answer_plan_join_request' req_id=req.id accept='ACCEPT' %}"
                   class="text-success">
                    {% trans "accept" %}
                </a>
            </td>
            <td>
                <a href="{% url 'planning:answer_plan_join_request' req_id=req.id accept='REJECT' %}"
                   class="text-danger">
                    {% trans "reject" %}
                </a>
            </td>
            {% endif %}

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
<div class="col-sm-1"></div>
{% endblock %}

src/planning/templates/planning/plan_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item">
    <a href="{% url 'planning:all_plans_list' %}">
        {% trans "plans" %}
    </a>
</li>

<li class="breadcrumb-item active">
    {{ plan.title }}
</li>
{% endblock %}

{% block content %}
<div class="col-sm-3" style="text-align: center;">
    <br/>
    {% if plan_participant.plan.head_man_user != request.user and plan_participant.plan.club.owner != request.user or plan_participant is None %}
        {% if plan_participant is None or plan_participant.status != "ACCEPTED" %}
            <a href="{% url 'planning:plan_participant_preregister' plan_id=plan.id %}" class="text-success">
                {% trans "join request" %}
            </a>
        {% elif plan_participant.status == "PENDING" %}
            <a href="{% url 'planning:answer_plan_join_request' req_id=plan_participant.id accept='REJECT' %}" class="text-danger">
                {% trans "cancel request" %}
            </a>
        {% endif %}

    {% else %}
        <a href="{% url 'planning:plan_edit' plan_id=plan.id %}">
            {% trans "edit" %}
        </a>
        <hr class="club-ops-hr">
    {% endif %}
</div>
<div class="col-sm-7">
    <br/>
    <table class="table">
        <tbody>
        <tr>
            <th scope="row">
                {% trans "title" %}
            </th>
            <td>
                {{ plan.title }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "description" %}
            </th>
            <td>
                {{ plan.description }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "destination_address" %}
            </th>
            <td>
                {{ plan.destination_address }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "group_link" %}
            </th>
            <td>
                {{ plan.group_link }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "start_datetime" %}
            </th>
            <td>
                {{ plan.start_datetime }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "club" %}
            </th>
            <td>
                {{ plan.club }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "head_man" %}
            </th>
            <td>
                {{ plan.head_man_user.first_name }}
                {{ plan.head_man_user.last_name }}
            </td>
        </tr>
        <tr>
            <th scope="row">
                {% trans "members" %}
            </th>
            <td>
                {{ plan.participants_cnt }} {% trans "persons" %}
                (<a href="{% url 'planning:plan_join_members_and_requests' plan_id=plan.id %}">{% trans "list" %}</a>)
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div class="col-sm-2"></div>
{% endblock %}

src/planning/templates/planning/plans_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
<li class="breadcrumb-item active">{% trans "plans" %}</li>
{% endblock %}

{% block content %}
<div class="col-sm-1"></div>
<div class="col-sm-10">
    {% if auth %}
        {% if my_plans %}
            <h4>{% trans "my plans" %}</h4>
            {% for plan in my_plans%}
                {% include 'planning/plan_card.html' with plan=plan %}
            {% endfor %}
        {% endif %}

        {% if pending_plans %}
        <h4>{% trans "pending plans" %}</h4>
            {% for plan in pending_plans%}
                {% include 'planning/plan_card.html' with plan=plan %}
            {% endfor %}
        {% endif %}

        {% if other_plans %}
            <h4>{% trans "other plans" %}</h4>
            {% for plan in other_plans%}
                    {% include 'planning/plan_card.html' with plan=plan %}
            {% endfor %}
            {% endif %}
        {% else %}
        <h4>{% trans "all plans" %}</h4>
        {% for plan in plans %}
        {% include 'planning/plan_card.html' with plan=plan %}
        {% endfor %}
    {% endif %}
</div>
<div class="col-sm-1"></div>
{% endblock %}